---
title: "tableone"
output:
  html_document: default
date: "2024-06-27"
---

```{r setup, include=FALSE, error=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, include=FALSE, error=FALSE}
library(tidyverse)
library(moments)
library(table1)
library(tableone)
library(ggmosaic)
library(corrplot)
load("C:/Users/xinbo/OneDrive/Desktop/LA's BeST/HELIX (2).RData")

```

```{r full table, error=FALSE}
ph=phenotype%>%
  mutate(hs_bmi_c_cat=fct_recode(hs_bmi_c_cat, 
                                    Underweight="1",
                                    Normal="2", 
                                    Overweight="3", 
                                    Obese="4"))
co=covariates%>%
  mutate(h_edumc_None=fct_recode(h_edumc_None, 
                                             'Primary'="1",
                                             'Secondary'="2",
                                             'University or Higher'="3"))%>%
  #will it cause issues to write it like that?
  mutate(h_parity_None=fct_recode(h_parity_None, `0`="0", `1`="1", `>1`="2"))%>%
  #does fct_recode change the order of the underlying factors?
  mutate(h_cohort=fct_recode(h_cohort, BiB="1", EDEN="2", INMA="3", KANC="4", MoBa="5", RHEA="6"))%>%
  mutate(e3_sex_None=fct_recode(e3_sex_None, Female="female", Male="male"))

total_merged=merge(co, exposome, by="ID")
total_merged2=merge(total_merged, ph, by="ID")

#mytable=CreateTableOne(data=merged) how to turn into a table?
#kableone(mytable) how to indent the levels?

label(total_merged2$e3_yearbir_None)='Birth Year'
label(total_merged2$h_cohort)='Cohort'
label(total_merged2$e3_sex_None)='Sex'
label(total_merged2$h_mbmi_None)='Maternal BMI'
label(total_merged2$hs_wgtgain_None)='Maternal Weight Gain (kg)'
label(total_merged2$e3_gac_None)='Gestational Age at Birth (wks)'
label(total_merged2$h_age_None)='Maternal Age (yrs)'
label(total_merged2$h_edumc_None)='Maternal Education Level'
label(total_merged2$h_native_None)='Number of Native Parents'
label(total_merged2$h_parity_None)='Prior Parity'
label(total_merged2$hs_child_age_None)='Child Age (yrs)'
label(total_merged2$hs_c_height_None)='Child Height (m)'
label(total_merged2$hs_c_weight_None)='Child Weight (kg)'
label(total_merged2$hs_bmi_c_cat)='BMI Category'
label(total_merged2$hs_zbmi_who)='BMI z-score'
label(total_merged2$hs_pfhxs_m_Log2)='PFHXS (ng/mL)*'
label(total_merged2$hs_pfna_m_Log2)='PFNA (ng/mL)*'
label(total_merged2$hs_pfoa_m_Log2)='PFOA (ng/mL)*'
label(total_merged2$hs_pfos_m_Log2)='PFOS (ng/mL)*'
label(total_merged2$hs_pfunda_m_Log2)='PFUNDA(ng/mL)*'
label(total_merged2$hs_total_fish_Ter)='Fish Consumption During Pregnancy (times/wk)'

#include sd of the PFAS like that or add in a row of the sd of the original data?
skewness(total_merged2$hs_pfhxs_m_Log2)
hist(total_merged2$hs_pfhxs_m_Log2)

#how skewed is too skewed to need to use median/IQR
#is it ok to not use the data that's in fully long format or will it cause issues
overall_table=table1(~ e3_yearbir_None+ h_cohort+e3_sex_None+ h_mbmi_None+ hs_wgtgain_None+e3_gac_None+ h_age_None+h_edumc_None+h_native_None+h_parity_None+hs_child_age_None+hs_c_height_None+hs_c_weight_None+hs_bmi_c_cat+hs_zbmi_who+hs_pfhxs_m_Log2+hs_pfna_m_Log2+hs_pfoa_m_Log2+hs_pfos_m_Log2+hs_pfunda_m_Log2+hs_total_fish_Ter,
       data=total_merged2, 
       render.continuous=c("Mean (SD)"), 
       caption="Mean (Standard Deviation) or Count (Proportion)",
       footnote="*Mean (SD) of base 2 log transformed data")
write.csv(overall_table, file="overall_table.csv")
overall_table


```

```{r}
#overall_tableone=CreateTableOne(data=merged2)
#as.data.frame(overall_tableone)
#overall_tableone <- print(overall_tableone, nonnormal = skewed, exact = "stage", quote = FALSE,
#noSpaces = TRUE, printToggle = FALSE)
#write.csv(overall_tableone, file="overall_tableone.csv")
```


```{r}
longmerged2=total_merged2%>%
  pivot_longer(cols=c(hs_pfhxs_m_Log2, hs_pfna_m_Log2, hs_pfoa_m_Log2, hs_pfos_m_Log2, hs_pfunda_m_Log2),
               names_to="PFAS",
               values_to="blood_conc")
longmerged2%>%
  ggplot(aes(x=hs_zbmi_who, y=blood_conc, color=PFAS))+
  geom_point()+
  theme_minimal()+
  labs(title="BMI z-score and Maternal PFAS Blood Concentration (ng/mL)",
       x="BMI z-score",
       y="Blood Concentration (ng/mL)")
```



```{r}
cohort_table=table1(~ e3_yearbir_None+e3_sex_None+ h_mbmi_None+ hs_wgtgain_None+e3_gac_None+ h_age_None+h_edumc_None+h_native_None+h_parity_None+hs_child_age_None+hs_c_height_None+hs_c_weight_None+hs_bmi_c_cat+hs_zbmi_who+hs_pfhxs_m_Log2+hs_pfna_m_Log2+hs_pfoa_m_Log2+hs_pfos_m_Log2+hs_pfunda_m_Log2+hs_total_fish_Ter| h_cohort, 
       data=total_merged2, 
       render.continuous=c("Mean (SD)"), 
       caption="Mean (Standard Deviation) or Count (Proportion) by Cohort",
       footnote="*Mean (SD) of base 2 log transformed data")
write.csv(cohort_table, file="cohort_table.csv")
cohort_table
#stratified=CreateTableOne(data=merged2, strata = "cohort")
#kableone(stratified)
```

```{r}
par(mfrow=c(2,3), oma=c(0,0,2,0), mar=c(4,5,2,0))
box_pfhxs=boxplot(total_merged2$hs_pfhxs_m_Log2~total_merged2$h_cohort,
                  xlab="Cohort",
                  cex.axis=0.65,
                  ylab="PFHXS (ng/mL)")
box_pfna=boxplot(total_merged2$hs_pfna_m_Log2~total_merged2$h_cohort,
                 xlab="Cohort",
                 cex.axis=0.65,
                 ylab="PFNA (ng/mL)")
box_pfoa=boxplot(total_merged2$hs_pfoa_m_Log2~total_merged2$h_cohort,
                 xlab="Cohort",
                 cex.axis=0.65,
                 ylab="PFOA (ng/mL)")
box_pfos=boxplot(total_merged2$hs_pfos_m_Log2~total_merged2$h_cohort,
                 xlab="Cohort",
                 cex.axis=0.65,
                 ylab="PFOS (ng/mL)")
box_pfunda=boxplot(total_merged2$hs_pfunda_m_Log2~total_merged2$h_cohort,
                  xlab="Cohort",
                  cex.axis=0.65,
                  ylab="PFUNDA (ng/mL)")
mtext("Maternal PFAS Blood Concentration (ng/mL) by Cohort", outer=TRUE)
```

```{r}
par(mfrow=c(2,3), oma=c(0,0,2,0), mar=c(4,5,2,0))
box_pfhxs=boxplot(total_merged2$hs_pfhxs_m_Log2~total_merged2$hs_total_fish_Ter,
                  xlab="Fish Consumption (times/wk)",
                  cex.axis=1,
                  ylab="PFHXS (ng/mL)")
box_pfna=boxplot(total_merged2$hs_pfna_m_Log2~total_merged2$hs_total_fish_Ter,
                 xlab="Fish Consumption (times/wk)",
                 cex.axis=1,
                 ylab="PFNA (ng/mL)")
box_pfoa=boxplot(total_merged2$hs_pfoa_m_Log2~total_merged2$hs_total_fish_Ter,
                 xlab="Fish Consumption (times/wk)",
                 cex.axis=1,
                 ylab="PFOA (ng/mL)")
box_pfos=boxplot(total_merged2$hs_pfos_m_Log2~total_merged2$hs_total_fish_Ter,
                 xlab="Fish Consumption (times/wk)",
                 cex.axis=1,
                 ylab="PFOS (ng/mL)")
box_pfunda=boxplot(total_merged2$hs_pfunda_m_Log2~total_merged2$hs_total_fish_Ter,
                  xlab="Fish Consumption (times/wk)",
                  cex.axis=1,
                  ylab="PFUNDA (ng/mL)")
mtext("Maternal PFAS Blood Concentration by Fish Consumption During Pregnancy", outer=TRUE)
```


```{r}
box_bmi=boxplot(longmerged2$hs_zbmi_who~longmerged2$h_cohort,
        main="BMI z-score by Cohort",
        xlab="Cohort",
        ylab="BMI z-score")
```


```{r}
bmi_table=table1(~ e3_yearbir_None+ h_cohort+e3_sex_None+ h_mbmi_None+ hs_wgtgain_None+e3_gac_None+ h_age_None+h_edumc_None+h_native_None+h_parity_None+hs_child_age_None+hs_c_height_None+hs_c_weight_None+hs_zbmi_who+hs_pfhxs_m_Log2+hs_pfna_m_Log2+hs_pfoa_m_Log2+hs_pfos_m_Log2+hs_pfunda_m_Log2+hs_total_fish_Ter| hs_bmi_c_cat, 
       data=total_merged2, 
       render.continuous=c("Mean (SD)"), 
       caption="Mean (Standard Deviation) or Count (Proportion) by BMI Category",
       footnote="*Mean (SD) of base 2 log transformed data")
write.csv(bmi_table, file="bmi_table.csv")
bmi_table
```

```{r}
#fix
#ggplot(longmerged2)+
   #geom_mosaic(aes(weight=1,x=product(maternal_education_level, cohort), fill=categorical_bmi))
mosaicplot(longmerged2$h_cohort ~ longmerged2$h_edumc_None,
           xlab="Cohort",
           cex.axis=0.55,
           ylab="Maternal Education Level",
           main="Maternal Education Level by Cohort")
#mosaic(~cohort +maternal_eduation_level+categorical_bmi, data=longmerged2)
```

```{r}
par(mfrow=c(2,3), oma=c(0,0,2,0), mar=c(4,5,2,0))
box_pfhxs=boxplot(total_merged2$hs_pfhxs_m_Log2~total_merged2$h_edumc_None,
                  xlab="Education Level",
                  cex.axis=0.55,
                  ylab="PFHXS (ng/mL)")
box_pfna=boxplot(total_merged2$hs_pfna_m_Log2~total_merged2$h_edumc_None,
                 xlab="Education Level",
                 cex.axis=0.55,
                 ylab="PFNA (ng/mL)")
box_pfoa=boxplot(total_merged2$hs_pfoa_m_Log2~total_merged2$h_edumc_None,
                 xlab="Education Level",
                 cex.axis=0.55,
                 ylab="PFOA (ng/mL)")
box_pfos=boxplot(total_merged2$hs_pfos_m_Log2~total_merged2$h_edumc_None,
                 xlab="Education Level",
                 cex.axis=0.55,
                 ylab="PFOS (ng/mL)")
box_pfunda=boxplot(total_merged2$hs_pfunda_m_Log2~total_merged2$h_edumc_None,
                  xlab="Education Level",
                  cex.axis=0.55,
                  ylab="PFUNDA (ng/mL)")
mtext("Maternal PFAS Blood Concentration (ng/mL) by Maternal Education Level", outer=TRUE)
```

```{r}
par(oma=c(0,0,1,0))
box_pfhxs=boxplot(total_merged2$hs_zbmi_who~total_merged2$h_edumc_None,
                  xlab="Education Level",
                  cex.axis=1,
                  ylab="BMI z-score")
mtext("BMI z-score by Maternal Education Level", outer=TRUE)
```



```{r}
#?
merged3=total_merged2%>%
  select("hs_zbmi_who", "hs_pfhxs_m_Log2","hs_pfna_m_Log2","hs_pfoa_m_Log2","hs_pfos_m_Log2","hs_pfunda_m_Log2")
merged3
corrplot(cor(merged3))

lm_model=lm(hs_zbmi_who~hs_pfhxs_m_Log2+hs_pfna_m_Log2+hs_pfoa_m_Log2+hs_pfos_m_Log2+hs_pfunda_m_Log2, 
            data=merged3)
summary(lm_model)

res=residuals(lm_model)
bmi=merged3$hs_zbmi_who
plot(res,bmi)
hist(res)
qqnorm(res)

lm_model2=lm(hs_zbmi_who~hs_pfna_m_Log2+hs_pfos_m_Log2, 
             data=merged3)
summary(lm_model2)

lm_model3=lm(hs_zbmi_who~., 
             data=total_merged2)
l3=summary(lm_model3)
coef(l3)[,"Pr(>|t|)"]
```

